name = "Synergy Mod Pack"; // name
picture = ""; // picture in expanded description
logoSmall = ""; // icon next to mod name when description is not expanded
logo = ""; // logo below game menu
logoOver = ""; // on mouse hover over logo
tooltip = "Synergy Mod Pack"; // tool tip on mouse hover
overview = ""; // overview
action = ""; // link
author = "colabus"; // author
version = "1.0"; // version